
# 공통

redis-key-prefix: 'auth:'

server:
  port: 8085

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    open-in-view: false # context 범위제한
    show-sql: true
  jwt:
    secret: 2021!!ZorupMSA
  messages:
    basename: i18n/exception
    encoding: UTF-8

noti-disable-api-url: http://localhost:8084/v1/user/

---


