
# 공통

redis-key-prefix: 'auth:'

server:
  port: 8085

spring:
  profiles:
    active: local   # 프로파일 지정 없으면 디폴트로 local 사용
  jpa:
    open-in-view: false # context 범위제한
    show-sql: true
  jwt:
    secret: 2021!!ZorupMSA
  messages:
    basename: i18n/exception
    encoding: UTF-8

noti-disable-api-url: http://localhost:8084/v1/user/

---

# 로컬 IDE기반 개발용 프로파일
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

---

# 로컬에서 도커로 띄워놓을때 사용하는 프로파일
spring:
  config:
    activate:
      on-profile: local-docker
  redis:
    host: host.docker.internal
    port: 6379
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb